-- 1. Profiles Tabelle anlegen (verknüpft mit dem Supabase Auth-System)
drop table if exists public.todos cascade;
drop table if exists public.appointments cascade;
drop table if exists public.books cascade;
drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security für Profiles aktivieren
alter table public.profiles enable row level security;
create policy "Jeder darf sein eigenes Profil sehen" on profiles for select using (auth.uid() = id);
create policy "Jeder darf sein eigenes Profil bearbeiten" on profiles for update using (auth.uid() = id);

-- Automatischer Trigger: Legt automatisch ein Profil an, wenn sich jemand neu registriert
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- WICHTIG: Falls schon Benutzer in Supabase registriert sind, Profile nachträglich anlegen:
insert into public.profiles (id, email)
select id, email from auth.users
where not exists (select 1 from public.profiles where profiles.id = auth.users.id);

-- 2. Books (Bücher) Tabelle anlegen
create table public.books (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null default auth.uid(),
  title text not null,
  color text,
  text_color text,
  type text not null default 'todo',
  is_locked boolean default false,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security für Bücher aktivieren
alter table public.books enable row level security;
create policy "Nutzer können nur ihre eigenen Bücher sehen/bearbeiten" on books for all using (auth.uid() = user_id);

-- 3. Todos (Aufgaben) Tabelle anlegen
create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null default auth.uid(),
  title text not null,
  book_id bigint references public.books(id) on delete cascade,
  repeat_type text default 'once',
  repeat_days integer[],
  repeat_dates integer[],
  date_str text,
  is_done boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security für Todos aktivieren
alter table public.todos enable row level security;
create policy "Nutzer können nur ihre eigenen Todos sehen/bearbeiten" on todos for all using (auth.uid() = user_id);

-- 4. Appointments (Termine) Tabelle anlegen
create table public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null default auth.uid(),
  title text not null,
  date_str text not null,
  time_str text,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security für Termine aktivieren
alter table public.appointments enable row level security;
create policy "Nutzer können nur ihre eigenen Termine sehen/bearbeiten" on appointments for all using (auth.uid() = user_id);

-- ==========================================
-- DEMO DATEN (Optional)
-- ==========================================
-- WICHTIG: Führe diesen Block erst aus, NACHDEM du dich einmal in der App registriert hast!
-- Das Skript sucht sich den zuerst registrierten Nutzer und füllt sein Profil mit Daten.

DO $$
DECLARE
  demo_user_id uuid;
  book1_id bigint;
  book2_id bigint;
BEGIN
  -- Hole die ID des ersten (oder neuesten) registrierten Nutzers
  SELECT id INTO demo_user_id FROM public.profiles LIMIT 1;
  
  IF demo_user_id IS NULL THEN
     RAISE EXCEPTION 'Kein Nutzer gefunden! Bitte registriere dich zuerst in der App über "Hier registrieren".';
  END IF;

  -- 1. Demo Bücher einfügen
  INSERT INTO public.books (user_id, title, color, text_color, type, is_locked)
  VALUES 
    (demo_user_id, 'Mein Journal', '#fce7f3', '#6b7280', 'todo', false)
  RETURNING id INTO book1_id;

  INSERT INTO public.books (user_id, title, color, text_color, type, is_locked)
  VALUES 
    (demo_user_id, 'Gesundheit', '#d1fae5', '#6b7280', 'todo', false)
  RETURNING id INTO book2_id;

  -- 2. Demo Todos einfügen
  INSERT INTO public.todos (user_id, title, book_id, repeat_type, date_str, is_done)
  VALUES 
    (demo_user_id, 'Morgenroutine (10 Min)', book1_id, 'daily', null, false),
    (demo_user_id, 'Tagebuch schreiben', book1_id, 'daily', null, false),
    (demo_user_id, 'Yoga (20 Min)', book2_id, 'daily', null, false),
    (demo_user_id, 'Wasser trinken (2 Liter)', book2_id, 'daily', null, true);

  -- 3. Demo Termine einfügen (Termine am aktuellen Tag)
  INSERT INTO public.appointments (user_id, title, date_str, time_str, color)
  VALUES 
    (demo_user_id, 'Lunch mit Sarah', to_char(now(), 'YYYY-MM-DD'), '12:30', '#fbcfe8'),
    (demo_user_id, 'Zahnarzt', to_char(now(), 'YYYY-MM-DD'), '16:00', '#bae6fd');

END $$;
